### ISSUE TITLE
1.20.1 Crashes when raising rate limit

### ISSUE THREAD

**Issue by RomeUnion373** [North-West-Wind/MekanismFissionRecipe#16]
When this mod is installed, if the rate limit of the fission reactor is raised to (I’m not sure of the exact number, but probably) 6 or higher, the temperature rises at an impossible rate and the game crashes. This occurred whether or not the JSON files for the coolant and nuclear waste recipes were present.

https://mclo.gs/AGXURxh

I'm writing an issue for the first time, and I'm not good at English. Sorry

**Comment by North-West-Wind** [comment]
Fixed in v3.0.3, which should be available soon.

**Comment by RomeUnion373** [comment]
Thank you for addressing the issue, I really appreciate it!

**Comment by RomeUnion373** [comment]
Sorry to bother you again, but I have another question. The crash has been resolved, but it still seems like the cooling of water and sodium isn't working properly. The temperature rise is abnormal. This happens even when no datapack is applied.

(I don't think it's related since it happens even without the datapack), but my code values might be wrong, so I'll paste them here. This is a direct copy of the code from the test datapack attached on GitHub.

```
{
  "type": "mekanism:fluid_coolant",
  "input": {
    "tag": "forge:water",
    "amount": 1
  },
  "output": {
    "gas": "mekanism:steam",
    "amount": 1
  },
  "thermalEnthalpy": 10,
  "conductivity": 0.5,
  "efficiency": 0.2
}
```

Sorry for troubling you while you're busy.

**Comment by North-West-Wind** [comment]
Fixed again in v3.0.4. Should be available soon.

**Comment by RomeUnion373** [comment]
sorry, thx!!!!

**Comment by RomeUnion373** [comment]
I'm sorry, the issue still persists. I apologize for bothering you so many times...

This is a comparison image of the temperature gauge when the rate limit is set to 10. The left shows Mekanism only, while the right includes this mod.
![レイヤー 2](https://github.com/user-attachments/assets/2be15d31-471a-48dd-a25c-4cf49b63cfe4)

**Comment by North-West-Wind** [comment]
Interesting. I did test it to make sure it was working. Maybe I should try a real mod loader environment.

**Comment by North-West-Wind** [comment]
Upon closer inspection, it's just my sloppy programming. But it seems like only fluid coolant is affected? Sodium seems fine.

**Comment by North-West-Wind** [comment]
Yet another version has released (v3.0.5).

**Comment by RomeUnion373** [comment]
It seems I was mistaken in mentioning sodium cooling as an example. I'll check it. Thank you!
